### ISSUE TITLE
Add an example of a BPMN diagram using bpmn-js

### ISSUE THREAD

**Issue by Mogztter** [yuzutech/kroki.io#11]
See: https://github.com/yuzutech/kroki/pull/178

**Comment by Mogztter** [comment]
@nekator by chance, do you have a sample diagram to share? not necessarily the most complex but a simplified real world example would be perfect.

**Comment by nekator** [comment]
Maybe you can use one from here https://github.com/bpmn-io/bpmn-js-examples 

All examples are under MIT license.

**Comment by Mogztter** [comment]
Thanks for the link!
I think I found the perfect example, pizza collaboration! https://github.com/bpmn-io/bpmn-js-examples/tree/master/colors :laughing:
