### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by MaKaNu** [yuzutech/kroki.io#117]
I always get an 504 if I try to use vega diagramms.

This is one of my diagramms:

https://kroki.io/vega/svg/eNqNVD2TmzAU7PkVjHIlY5O7OMW1bpKZpEx14-KBHqBYSB4hbDMe__eTxIcFtpVQwUq7evveoksUm4e8NHmFNZD3mFRaH5r39fqIJaxKpqs2WzG57jc4dH3crP42UpCkJ58Y1ZWhfk3TdIAqZGWlDfY6QQeglInSYJsk6iEK2h754b7sc5neiIAabTkaMo7DSW7hCLzFZkZzVJKDxlKqzrK2immWAydJTKCWrbC1pOYjl1wqu-NLUZhyU3JNAjI_jIugBGz-JfEbKWvrgAgFW0lY5Jc8BRTS1GqEFf6IvZAnEVDJCnzLvoVVfopCBgvpWzop7Ka3HtuNk2_MbBZDfDD7s9vmD193B7eSgaA-TmUNTJiVyxiqMTgxKRhyapHJieeRKBClk-xT7K3cApuu0o1PMeatoFYt3gwmISfdnZP_qnjos1-vYDkOZz9yMfx4z_oO52XXYyIVQzdMkkmtpctqX643gphwyJBvx1mfKqaRzFz7ShwLPdPpgjoJMX_rfjuE6vuy6hrU_mlYxkgozLXf4EIZK7f2Dt31W4kil9RyL7PIG1yjuofPTu1BZ4IBm92QD-kuy-b2XJK6OaG7P-8-Hj3x9RnT3Z020EtKwTh3pHHH8FfP3DnkOiNeo2dvu-gafQKsOJeZ

The Result on the website looks like this:

![image](https://github.com/yuzutech/kroki.io/assets/32844273/7530b4f9-f3fe-4589-a40c-993bbb190293)

so this also happens for diagramms we create in gitlab wiki.

I also tested different schemes same result.

**Comment by ggrossetie** [comment]
It seems that the gateway server of the public instance is experiencing issues.

I'm currently on vacation, so I won't be able to fix it until next week or so.

As a workaround, you can install Kroki on your own infrastructure.

In the future, and if there is enough demand, we could consider implementing a paid service with a Service Level Agreement (SLA) and guarantees on service availability. We might even provide dedicated instances per client.

Out of curiosity, is this something that you or your company would be interested in?

**Comment by MaKaNu** [comment]
First at all have a nice Vacation sorry to bother you.

Our demand is not very high. Actually we using kroki for our custom wiki sast report because we as university department have always issues with abo models. So we are only missing the statistic bar diagram at the moment. I actually planned to set up an instance in the future, but it has based on the little use case at the moment not the highest prio.

So SLA is mostly something that is for us not very necessary as well as the service availability.

**Comment by ggrossetie** [comment]
Thanks for your input. It's now fixed 😄
