### ISSUE TITLE
No License in REPO

### ISSUE THREAD

**Issue by wico-heuschkel** [yuzutech/kroki.io#123]
Hello, can you please put a license in your repo ?
BR JH

**Comment by ggrossetie** [comment]
Hello, are you talking about the license of "kroki" (the service/tool) or the actual license of the kroki.io website?

**Comment by wico-heuschkel** [comment]
Hi! I talk about the kroki.io website. Especially about the "try" part. The license for kroki is clear, as there is a license file in the repo :)

**Comment by ggrossetie** [comment]
Aright, I've just added a license 😉 
https://github.com/yuzutech/kroki.io/commit/fc0451239c469dca579e239e90f440c23032372c

**Comment by wico-heuschkel** [comment]
Thank you very much :)
