### ISSUE TITLE
Examples are loading as single line on firefox

### ISSUE THREAD

**Issue by hugosenari** [yuzutech/kroki.io#18]
Hello,

To me on Firefox/Linux, examples from front page are loading as single line.

The problem: `white-space: nowrap;`
Firefox/Chrome  implementation of nowrap differs for textearea.

Curiously in [dev moz](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) Chrome works as Firefox :confused: 

edit: better bug description :)

**Comment by Mogztter** [comment]
Hello @hugosenari 

Could you please provide a screenshot, I'm not sure I quite understand the issue.


Thanks,
Guillaume

**Comment by hugosenari** [comment]
![image](https://user-images.githubusercontent.com/863299/89082956-014a6880-d366-11ea-9c42-2a018eb50742.png)

**Comment by Mogztter** [comment]
Oh I see... `white-space: pre;` seems to produce the expected result in Firefox, Safari and Chrome. I will update the stylesheet.

Thanks for the heads up!

**Comment by Mogztter** [comment]
This change is now live :tada:
